name: CI

on:
  push:
    branches:
      - main
  pull_request:

# Automatically cancel previous workflow runs when a new commit is pushed.
concurrency:
  group: lint-test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: cargo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: cargo check
        run: cargo check
      - name: cargo test
        run: cargo test
      - name: Check formatting
        run: cargo fmt --check
      - name: Check clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
